/**
 * Skills Markdown Writer
 *
 * Generates a human-readable `skills.md` summary of every skill that
 * the catalog detector can see for a project, grouped by source and
 * annotated with the changes detected by `SkillChangeDetector`.
 *
 * Used by the `/init` command to materialise a project-root
 * documentation file on first run and to keep it in sync on
 * subsequent runs.
 */
import { promises as fs } from "node:fs";
import path from "node:path";
import {
  discoverSkillCatalog,
  type SkillCatalogEntry,
  type SkillCatalogSource,
} from "@/skills/catalog.js";
import {
  createSkillChangeDetector,
  type SkillChangeEvent,
  type SkillChangeType,
} from "@/utils/skills/skillChangeDetector.js";
import { h1, h2, h3, bold, hr, table } from "@/utils/markdown.js";
import logger from "@/utils/logger.js";

export const SKILLS_MD_FILENAME = "skills.md";

export type SkillsMarkdownSkill = SkillCatalogEntry;

export interface WriteSkillsMarkdownOptions {
  /** Optional pre-resolved skill list. When omitted the writer calls
   *  `discoverSkillCatalog` internally. */
  skills?: SkillCatalogEntry[];
  /** If false and the file already exists, the writer leaves it alone.
   *  Default: true (idempotent overwrite). */
  overwrite?: boolean;
  /** Pre-computed change events. When omitted the writer runs the
   *  `SkillChangeDetector` for the project root. */
  changes?: SkillChangeEvent[];
}

export interface WriteSkillsMarkdownResult {
  path: string;
  written: boolean;
  skillCount: number;
  changeCount: number;
}

const SOURCE_HEADINGS: Record<SkillCatalogSource, string> = {
  project: "Project Skills",
  global: "Global Skills",
  embedded: "Embedded Skills",
  vendored: "Vendored Skills",
};

const CHANGE_VERBS: Record<SkillChangeType, string> = {
  added: "Added",
  removed: "Removed",
  modified: "Modified",
};

/**
 * Escape a string for safe inclusion in a markdown list item.
 *
 * Bullet lists do not interpret markdown inside them, but we still
 * collapse newlines and trim so descriptions render on a single line
 * and we never accidentally open or close a code span.
 */
function sanitizeDescription(description: string): string {
  return description
    .replace(/\r?\n+/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

/**
 * Build the markdown body for a single skill entry.
 * Format: `- **name** — description`
 */
function formatSkillLine(skill: SkillCatalogEntry): string {
  const description = sanitizeDescription(skill.description) || "_no description_";
  return `- ${bold(skill.name)} — ${description}`;
}

/**
 * Build the markdown body for a single change event.
 */
function formatChangeLine(change: SkillChangeEvent): string {
  const verb = CHANGE_VERBS[change.type];
  return `- ${bold(change.skillName)} — ${verb} (source: ${change.source})`;
}

/**
 * Group skills by their catalog source so the section reads naturally.
 * The output preserves the SOURCE_HEADINGS ordering for stability.
 */
function groupBySource(skills: SkillCatalogEntry[]): Map<SkillCatalogSource, SkillCatalogEntry[]> {
  const groups = new Map<SkillCatalogSource, SkillCatalogEntry[]>();
  for (const source of Object.keys(SOURCE_HEADINGS) as SkillCatalogSource[]) {
    groups.set(source, []);
  }
  for (const skill of skills) {
    const bucket = groups.get(skill.source);
    if (bucket) {
      bucket.push(skill);
    }
  }
  return groups;
}

function renderSkillsMarkdown(
  skills: SkillCatalogEntry[],
  changes: SkillChangeEvent[],
  projectRoot: string,
): string {
  const today = new Date().toISOString().slice(0, 10);
  const lines: string[] = [];

  lines.push(h1("Skills").trimEnd());
  lines.push("");
  lines.push(
    `> Auto-generated by \`pakalon /init\` on ${today}. Detected ${skills.length} skill(s) for project \`${path.basename(projectRoot) || projectRoot}\`.`,
  );
  lines.push("");

  // --- Available Skills -----------------------------------------------------
  lines.push(h2("Available Skills").trimEnd());
  lines.push("");

  if (skills.length === 0) {
    lines.push(
      "_No skills detected. Add a `SKILL.md` to one of the project skill roots (`.pakalon/skills/`, `.claude/skills/`, `.agents/skills/`, `.pakalon-agents/skills/`) to register a new skill._",
    );
    lines.push("");
  } else {
    const groups = groupBySource(skills);
    let firstGroup = true;
    for (const [source, entries] of groups) {
      if (entries.length === 0) continue;
      if (!firstGroup) {
        lines.push("");
      }
      firstGroup = false;
      lines.push(h3(SOURCE_HEADINGS[source]).trimEnd());
      lines.push("");
      for (const skill of entries) {
        lines.push(formatSkillLine(skill));
      }
      lines.push("");
    }
  }

  // --- Recently Changed -----------------------------------------------------
  lines.push(h2("Recently Changed").trimEnd());
  lines.push("");

  if (changes.length === 0) {
    lines.push("_No skill changes detected since the last `/init` run._");
    lines.push("");
  } else {
    const byType = new Map<SkillChangeType, SkillChangeEvent[]>();
    for (const event of changes) {
      const bucket = byType.get(event.type) ?? [];
      bucket.push(event);
      byType.set(event.type, bucket);
    }
    for (const type of ["added", "modified", "removed"] as SkillChangeType[]) {
      const events = byType.get(type);
      if (!events || events.length === 0) continue;
      lines.push(h3(CHANGE_VERBS[type]).trimEnd());
      lines.push("");
      for (const event of events) {
        lines.push(formatChangeLine(event));
      }
      lines.push("");
    }
  }

  // --- Source Roots --------------------------------------------------------
  lines.push(h2("Source Roots").trimEnd());
  lines.push("");
  const seenRoots = new Set<string>();
  const rootRows: Array<{ Source: string; Path: string }> = [];
  for (const skill of skills) {
    if (seenRoots.has(skill.rootDir)) continue;
    seenRoots.add(skill.rootDir);
    rootRows.push({
      Source: SOURCE_HEADINGS[skill.source] ?? skill.source,
      Path: skill.rootDir,
    });
  }
  if (rootRows.length === 0) {
    lines.push("_No skill source roots were scanned._");
    lines.push("");
  } else {
    lines.push(table(["Source", "Path"], rootRows).trimEnd());
    lines.push("");
  }

  lines.push(hr().trimEnd());
  lines.push("");
  lines.push(
    `*Do not edit this file by hand — it is regenerated on every \`/init\` run.*`,
  );
  lines.push("");

  return lines.join("\n");
}

/**
 * Write a human-readable `skills.md` to the project root.
 *
 * The function uses the existing `discoverSkillCatalog` to enumerate
 * skills and the `SkillChangeDetector` to discover which skills have
 * been added, modified, or removed since the previous run. It never
 * duplicates detection logic.
 *
 * @param projectRoot  Absolute path to the project root.
 * @param skills       Pre-resolved skills list. When omitted the
 *                     writer calls `discoverSkillCatalog` internally.
 * @param options      Optional overrides (idempotency flag, change events).
 * @returns The path written, whether a write actually happened, and counts.
 */
export async function writeSkillsMarkdown(
  projectRoot: string,
  skills?: SkillCatalogEntry[],
  options?: WriteSkillsMarkdownOptions,
): Promise<WriteSkillsMarkdownResult> {
  const resolvedRoot = path.resolve(projectRoot);
  const outPath = path.join(resolvedRoot, SKILLS_MD_FILENAME);
  const overwrite = options?.overwrite ?? true;

  let resolvedSkills: SkillCatalogEntry[];
  if (options?.skills) {
    resolvedSkills = options.skills;
  } else if (skills) {
    resolvedSkills = skills;
  } else {
    resolvedSkills = discoverSkillCatalog({
      includeContent: false,
      projectDir: resolvedRoot,
    });
  }

  let changes: SkillChangeEvent[];
  if (options?.changes) {
    changes = options.changes;
  } else {
    const detector = createSkillChangeDetector({ projectDir: resolvedRoot });
    changes = await detector.scanForChanges();
  }

  const content = renderSkillsMarkdown(resolvedSkills, changes, resolvedRoot);

  await fs.mkdir(path.dirname(outPath), { recursive: true });

  let written = true;
  if (!overwrite) {
    try {
      await fs.access(outPath);
      written = false;
    } catch {
      // File does not exist — we will write it below.
    }
  }

  if (written) {
    await fs.writeFile(outPath, content, "utf-8");
    logger.info("[skillsMarkdownWriter] wrote skills.md", {
      path: outPath,
      skills: resolvedSkills.length,
      changes: changes.length,
    });
  }

  return {
    path: outPath,
    written,
    skillCount: resolvedSkills.length,
    changeCount: changes.length,
  };
}
