/**
 * Single-file CHANGELOG.md generator.
 *
 * Aggregates entries from:
 *   - Git log (if available)
 *   - .pakalon-agents/ai-agents/phase-* outputs
 *   - Manual entries from plan.md
 *
 * Output follows "Keep a Changelog" 1.1.0
 *   https://keepachangelog.com/en/1.1.0
 */
import * as fs from "fs";
import * as fsp from "fs/promises";
import * as path from "path";
import { execFile } from "child_process";
import { promisify } from "util";
import logger from "@/utils/logger.js";

const execFileAsync = promisify(execFile);

type Section = "Added" | "Changed" | "Deprecated" | "Removed" | "Fixed" | "Security";

export interface ChangelogOptions {
  projectDir: string;
  /** Optional tag to start from. Defaults to all commits. */
  sinceTag?: string;
  /** Version to anchor this changelog to (e.g. "1.0.0") */
  version?: string;
}

export async function writeChangelog(options: ChangelogOptions): Promise<string> {
  const file = path.join(options.projectDir, "CHANGELOG.md");
  const sections: Record<Section, string[]> = {
    Added: [],
    Changed: [],
    Deprecated: [],
    Removed: [],
    Fixed: [],
    Security: [],
  };

  // 1) Git log
  try {
    const args = ["log", "--pretty=format:%H\u241f%s"];
    if (options.sinceTag) args.unshift(`${options.sinceTag}..HEAD`);
    const { stdout } = await execFileAsync("git", args, {
      cwd: options.projectDir,
      maxBuffer: 10 * 1024 * 1024,
    });
    for (const line of stdout.split(/\r?\n/)) {
      const [hash, ...rest] = line.split("\u241f");
      if (!hash) continue;
      const message = rest.join("\u241f");
      const section = categorize(message);
      sections[section].push(`- ${message} (${hash.slice(0, 7)})`);
    }
  } catch {
    // not a git repo — that's fine
  }

  // 2) Phase outputs
  try {
    const aiAgentsDir = path.join(options.projectDir, ".pakalon-agents", "ai-agents");
    const entries = await fsp.readdir(aiAgentsDir);
    for (const entry of entries) {
      if (!entry.startsWith("phase-")) continue;
      const phaseFile = path.join(aiAgentsDir, entry, "phase-summary.md");
      try {
        const stat = await fsp.stat(phaseFile);
        if (stat.isFile()) {
          sections.Added.push(`- Phase ${entry.replace("phase-", "")} deliverable (see ${path.relative(options.projectDir, phaseFile)})`);
        }
      } catch {
        // skip
      }
    }
  } catch {
    // no .pakalon-agents dir yet
  }

  // 3) Render
  const ver = options.version ?? "Unreleased";
  const date = new Date().toISOString().slice(0, 10);
  const body = (Object.entries(sections) as Array<[Section, string[]]>)
    .map(([sec, items]) => {
      const list = items.length ? items.join("\n") : "- No entries.";
      return `### ${sec}\n\n${list}`;
    })
    .join("\n\n");

  const content = `# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.1.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

## [${ver}] - ${date}

${body}

---
_Generated by Pakalon Phase 6 on ${new Date().toISOString()}_
`;

  await fsp.writeFile(file, content, "utf-8");
  logger.info({ file, version: ver }, "CHANGELOG.md written");
  return file;
}

function categorize(message: string): Section {
  const lower = message.toLowerCase();
  if (/^(feat|add)/.test(lower) || /\badd(ed|ition)?\b/.test(lower)) return "Added";
  if (/^(fix|bug)/.test(lower) || /\bfix(ed|es)?\b/.test(lower)) return "Fixed";
  if (lower.includes("security") || lower.includes("cve")) return "Security";
  if (/^(refactor|chore|perf|style|docs?)/.test(lower)) return "Changed";
  if (lower.startsWith("deprecate")) return "Deprecated";
  if (/^(remove|delete|drop)/.test(lower)) return "Removed";
  return "Changed";
}

// Convenience wrapper for backward compatibility with the existing
// generateChangelog(projectDir, sinceTag) signature.
export async function generateChangelog(projectDir: string, sinceTag?: string): Promise<string> {
  return writeChangelog({ projectDir, sinceTag });
}
