/**
 * Doc.md generator — produces a single end-user-facing documentation
 * file by aggregating every artifact the 6 phases have produced.
 *
 * Sections mirror CLI-req §"Phase 6":
 *   - Overview
 *   - Features (from user-stories)
 *   - Architecture (from plan/design)
 *   - How to install / run (from phase-3 outputs)
 *   - Tech stack (from plan.md)
 *   - API reference (from phase-3 backend output)
 *   - Configuration
 *   - Troubleshooting
 */
import * as fs from "fs/promises";
import * as path from "path";
import { generateText } from "ai";
import { openrouter } from "@openrouter/ai-sdk-provider";
import logger from "@/utils/logger.js";

export interface DocGeneratorOptions {
  projectDir: string;
  /** Force a re-summarization even if Doc.md already exists */
  force?: boolean;
  /** Output filename (default: Doc.md) */
  filename?: string;
}

const ROOT = ".pakalon-agents/ai-agents";
const FILES = {
  plan: "plan.md",
  tasks: "tasks.md",
  stories: "user-stories.md",
  design: "design.md",
  brainstorm: "phase-1/brainstorm.json",
} as const;

export async function generateDoc(options: DocGeneratorOptions): Promise<string> {
  const filename = options.filename ?? "Doc.md";
  const out = path.join(options.projectDir, filename);

  if (!options.force) {
    try {
      await fs.access(out);
      logger.info({ file: out }, "Doc.md already exists; skipping (use force:true to regenerate)");
      return out;
    } catch {
      // continue
    }
  }

  const root = path.join(options.projectDir, ROOT);
  const sections = await collectSections(root);

  const summary = await summarize(sections);
  await fs.promises.writeFile(out, summary, "utf-8");
  logger.info({ file: out, bytes: summary.length }, "Doc.md generated");
  return out;
}

interface CollectedSection {
  source: string;
  content: string;
}

async function collectSections(root: string): Promise<CollectedSection[]> {
  const out: CollectedSection[] = [];
  for (const [, rel] of Object.entries(FILES)) {
    try {
      const content = await fs.promises.readFile(path.join(root, rel), "utf-8");
      out.push({ source: rel, content });
    } catch {
      // missing is fine; we just skip
    }
  }
  return out;
}

async function summarize(sections: CollectedSection[]): Promise<string> {
  if (sections.length === 0) {
    return defaultTemplate("");
  }
  try {
    const inputBlob = sections
      .map((s) => `=== ${s.source} ===\n${s.content.slice(0, 4000)}`)
      .join("\n\n");
    const result = await generateText({
      model: openrouter("anthropic/claude-3-5-haiku"),
      system: DOC_SYSTEM_PROMPT,
      prompt: inputBlob,
      maxTokens: 4096,
    });
    return defaultTemplate(result.text);
  } catch (err) {
    logger.warn({ err }, "Doc.md LLM summarization failed, writing static template");
    return defaultTemplate(sections.map((s) => `From ${s.source}:\n\n${s.content.slice(0, 1500)}`).join("\n\n---\n\n"));
  }
}

const DOC_SYSTEM_PROMPT = `You are a senior technical writer. Produce a single, end-user-facing documentation file.
The output must use markdown headings exactly in this order:
# Overview
# Features
# Architecture
# How to install and run
# Tech stack
# API reference
# Configuration
# Troubleshooting

Use concise bullet points. Avoid empty sections — if a section has no source, write a single bullet saying "Not specified in plan".`;

function defaultTemplate(body: string): string {
  const sections = [
    "Overview",
    "Features",
    "Architecture",
    "How to install and run",
    "Tech stack",
    "API reference",
    "Configuration",
    "Troubleshooting",
  ];
  const head = `# Documentation\n\n_Generated by Pakalon Phase 6 Doc.md generator._\n\n`;
  const skeleton = sections
    .map((s) => `## ${s}\n\n${body || "_No source material available._"}\n`)
    .join("\n");
  return head + skeleton;
}
