/**
 * /auto-fix-pr — open a PR with auditor findings auto-applied.
 *
 * Combines `suggest-pr` with the auditor loop. Phase 4 (testing) calls
 * this when it discovers fixable issues, so the user has the option to
 * merge the patch.
 */
import { suggestBackgroundPR, type SuggestPrResult } from "@/commands/suggest-pr.js";
import { runAuditor, type AuditorResult } from "@/agents/auditor/index.js";
import logger from "@/utils/logger.js";

export interface AutoFixPrOptions {
  projectDir: string;
  phase?: number;
  /** Open the PR with the gh CLI when true */
  openWithGh?: boolean;
}

export interface AutoFixPrResult {
  auditor: AuditorResult;
  pr: SuggestPrResult;
  prUrl?: string;
  opened: boolean;
}

export async function autoFixPr(opts: AutoFixPrOptions): Promise<AutoFixPrResult> {
  const auditor = await runAuditor(opts.projectDir, {
    readOnly: false,
    autoRemediate: true,
    maxIterations: 5,
  });
  logger.info({ findings: auditor.findings.length }, "Auditor completed; opening auto-fix PR");
  const pr = await suggestBackgroundPR({ projectDir: opts.projectDir, phase: opts.phase });

  let prUrl: string | undefined;
  let opened = false;
  if (opts.openWithGh && pr.pushed) {
    const { execFile } = await import("child_process");
    const { promisify } = await import("util");
    const execFileAsync = promisify(execFile);
    try {
      const title = pr.commitMessage;
      const { stdout } = await execFileAsync(
        "gh",
        ["pr", "create", "--base", "main", "--head", pr.branch, "--title", title, "--body", `Auto-generated by Pakalon.\n\n${pr.body}`],
        { cwd: opts.projectDir },
      );
      prUrl = stdout.trim().split(/\r?\n/).pop();
      opened = true;
    } catch (err) {
      logger.warn({ err }, "gh pr create failed");
    }
  }

  return { auditor, pr, prUrl, opened };
}
