/**
 * /suggest-pr — open a PR with the current uncommitted changes.
 *
 * Generates a branch name + commit message + PR body from the diff
 * and (optionally) the running phase. Used by the auditor and the
 * Phase 5 deploy agent.
 */
import { execFile } from "child_process";
import { promisify } from "util";
import logger from "@/utils/logger.js";

const execFileAsync = promisify(execFile);

export interface SuggestPrOptions {
  projectDir: string;
  /** Phase number used in the branch + PR title (e.g. 4). */
  phase?: number;
  /** Force overwrite an existing branch. */
  force?: boolean;
}

export interface SuggestPrResult {
  branch: string;
  commitMessage: string;
  body: string;
  pushed: boolean;
  url?: string;
}

async function run(cmd: string, args: string[], cwd: string): Promise<string> {
  try {
    const { stdout } = await execFileAsync(cmd, args, { cwd });
    return stdout.trim();
  } catch (err) {
    logger.debug({ err, cmd, args }, "git command failed");
    throw err;
  }
}

export async function suggestBackgroundPR(opts: SuggestPrOptions): Promise<SuggestPrResult> {
  const { projectDir, phase } = opts;
  const branch = phase ? `phase-${phase}/auto-fix-${Date.now()}` : `auto-fix-${Date.now()}`;
  const status = await run("git", ["status", "--porcelain"], projectDir).catch(() => "");
  if (!status) {
    return { branch, commitMessage: "(no changes)", body: "_No local changes to commit._", pushed: false };
  }

  await run("git", ["checkout", "-B", branch], projectDir);
  await run("git", ["add", "-A"], projectDir);
  const commitMessage = phase ? `fix(phase-${phase}): automated remediation` : "fix: automated remediation";
  await run("git", ["commit", "-m", commitMessage, "-m", "Generated by /suggest-pr from Pakalon."], projectDir);
  let pushed = false;
  try {
    await run("git", ["push", "-u", "origin", branch, ...(opts.force ? ["--force"] : [])], projectDir);
    pushed = true;
  } catch {
    pushed = false;
  }
  return { branch, commitMessage, body: status, pushed };
}
